### PR TITLE
Multi guild support?!

### PR DESCRIPTION
**Pull request by Bottersnike**
Multi guild support's back!
===
The blacklist and queue have been modified to function over multiple guilds at the same time. Likes are still global.

### TODO:
- [ ] Make likes per-guild?
- [ ] Add the invite URL back
- [x] Add commands to allow server owners to setup default channels.
- [ ] Make permissions settable by guild owners and mods.

### CODE REVIEW

**Comment by Noahkiq** [comment]
mulit guilds

**Comment by qixils** [comment]
will we be making htbote public? 🤔

**Comment by Bottersnike** [comment]
Not sure. To be fair, I decided to do it just to make certain things easier and make the bot more accessable to the HTC-family of servers (hence the `?` by the first checkbox)

**Comment by qixils** [comment]
patron-only maybe? not sure how we could set that up tho

**Comment by hanss314** [comment]
I don't think we should make likes multi guild, unless we're making HTBote fully public which I do not support.

**Comment by hanss314** [comment]
Does this work now? If so I'll merge.

**Pull request merged**
