### PR TITLE
Christmas Autoplaylist

### PR DESCRIPTION
**Pull request by qixils**
Send submissions for the XmasAP here! Or make a fork and edit in links... or maybe I should setup a google form...

### CODE REVIEW

**Comment by hanss314** [comment]
This will break the autoplaylist

**Comment by hanss314** [comment]
wait nvm

**Comment by hanss314** [comment]
crap clicking wrong buttons

**Comment by qixils** [comment]
thanks for the feedback hanss

**Comment by hanss314** [comment]
We can close this now. Guess it didn't work out.

**Pull request closed without merging**
